baseURL = "https://mgsoftware.github.io/"
languageCode = "en-us"
title = "MG Software Blog"
theme = "PaperMod"

# Syntax highlighting
[markup]
  [markup.highlight]
    style = "dracula"
    guessSyntax = true
    lineNos = true
    noClasses = false

[params]
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  defaultTheme = "auto"
  disableThemeToggle = false