baseURL = "https://mgrzegorczyk.github.io/"
languageCode = "en-us"
title = "<MG / Software>"
theme = "PaperMod"

[pagination]
  pagerSize = 3

[taxonomies]
  tag = "tags"

[markup]
  [markup.highlight]
    style = "dracula"
    guessSyntax = true
    lineNos = true
    noClasses = false
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowCodeCopyButtons = true
  defaultTheme = "auto"
  DisableSpecial1stPost = true

[menu]
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 1

  [[menu.main]]
    identifier = "tags"
    name = "Hashtags"
    url = "/tags/"
    weight = 2

  [[menu.main]]
    name = "Author"
    url = "/author/"
    weight = 3

